name: vokaflow # Vokaflow - AI Assistant & Translation App
description: "📱 VokaFlow App Final – Comunicación Multilingüe Invisible"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # UI & Design
  cupertino_icons: ^1.0.6
  flutter_svg: ^2.0.9
  google_fonts: ^6.2.1
  lottie: ^3.0.0
  flutter_animate: ^4.5.0
  shimmer: ^3.0.0
  
  # Navigation & State Management
  go_router: ^14.2.0
  provider: ^6.0.5
  riverpod: ^2.4.9
  flutter_riverpod: ^2.4.9
  
  # Localization
  easy_localization: ^3.0.7
  
  # Storage & Preferences
  shared_preferences: ^2.2.2
  sqflite: ^2.3.0
  path: ^1.8.3
  
  # Network & API
  http: ^1.2.0
  dio: ^5.4.0
  web_socket_channel: ^2.4.0
  
  # Firebase & Authentication
  firebase_core: ^3.13.1
  firebase_auth: ^5.5.4
  google_sign_in: ^6.3.0
  cloud_firestore: ^5.6.8
  firebase_storage: ^12.4.6
  
  # Local Storage & Notifications
  flutter_local_notifications: ^17.2.1
  path_provider: ^2.1.2
  logger: ^2.0.2+1

  # Media & Camera
  camera: ^0.10.5+5
  image_picker: ^1.0.4
  video_player: ^2.8.1
  audioplayers: ^5.2.1
  record: ^5.0.4
  permission_handler: ^11.1.0
  
  # Voice & Speech
  speech_to_text: ^7.0.0
  flutter_tts: ^3.8.5
  
  # Image Processing
  image: ^4.1.3
  google_ml_kit: ^0.20.0
  google_mlkit_commons: ^0.11.0
  google_mlkit_translation: ^0.13.0
  google_mlkit_text_recognition: ^0.15.0
  google_mlkit_smart_reply: ^0.13.0
  
  # Video Calling
  agora_rtc_engine: ^6.3.0
  
  # Utils
  uuid: ^4.2.1
  intl: ^0.19.0
  url_launcher: ^6.2.2
  package_info_plus: ^8.3.0
  device_info_plus: ^9.1.1
  connectivity_plus: ^5.0.2
  
  # Security
  local_auth: ^2.1.8
  
  # Development
  flutter_dotenv: ^5.1.0
  
  # Missing Dependencies
  equatable: ^2.0.5
  flutter_advanced_drawer: ^1.3.6
  cached_network_image: ^3.4.1
  dropdown_button2: ^2.3.9

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1

  
flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/animations/
    - assets/audio/
    - assets/translations/
    - .env

# Flutter Launcher Icons Configuration
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo.png"
  min_sdk_android: 21
  web:
    generate: true
    image_path: "assets/images/logo.png"
    background_color: "#FFFFFF"
    theme_color: "#E91E63"
  windows:
    generate: true
    image_path: "assets/images/logo.png"
    icon_size: 48
  macos:
    generate: true
    image_path: "assets/images/logo.png"
