# Configuración Optimizada de Vicky (IA de VokaFlow)
core:
  name: Vicky
  version: 0.2.0
  log_level: INFO

# Configuración de modelos optimizada
models:
  language_model:
    type: qwen
    path: /cache/vokaflow_models/qwen
    quantization: 4bit        # Balance óptimo entre rendimiento y calidad
    device: cpu               # Ajustar a cuda si hay GPU disponible
    context_length: 4096      # Aumentado para mejor manejo de contexto
    preload: true             # Cargar al inicio para menor latencia
    batch_size: 1             # Optimizado para consultas individuales
    model_parameters:
      temperature: 0.75       # Balance entre creatividad y precisión
      top_p: 0.9              # Muestreo núcleo para coherencia
      top_k: 40               # Diversidad controlada
  
  translation_model:
    type: nllb
    path: /cache/vokaflow_models/nllb
    device: cpu               # Ajustar a cuda si hay GPU disponible
    supported_languages: 200
    quantization: 8bit        # Suficiente para traducción de calidad
    batch_size: 8             # Optimizado para traducción por lotes
  
  speech_recognition:
    type: whisper
    path: /cache/vokaflow_models/whisper
    device: cpu               # Ajustar a cuda si hay GPU disponible
    language: auto
    model_size: "medium"      # Balance entre precisión y velocidad
    beam_size: 5              # Búsqueda de haz para mejor precisión
  
  text_to_speech:
    type: xtts
    path: /cache/vokaflow_models/tts
    device: cpu               # Ajustar a cuda si hay GPU disponible
    language: auto
    voice_quality: "high"     # Alta calidad de voz
    sample_rate: 24000        # Frecuencia de muestreo óptima
  
  embeddings:
    type: sentence-transformers
    path: /cache/vokaflow_models/embeddings
    device: cpu               # Ajustar a cuda si hay GPU disponible
    dimension: 384
    pooling: "mean"           # Estrategia de pooling óptima
    normalize: true           # Normalizar embeddings para mejor similitud

# Configuración para el generador de respuestas
response_generator:
  default_response_type: text
  default_content_format: markdown
  enable_voice: true
  enable_multimodal: true
  max_response_length: 2000
  enable_suggestions: true
  enable_sources: true
  sentiment_analysis: true
  contextual_suggestions: true
  hemisphere_adaptation: true
  enable_factuality_check: true
  hemisphere_combiner:
    default_strategy: hybrid_fusion
    strategy_weights:
      technical: 0.6
      emotional: 0.4
    query_type_config:
      technical: ["code", "data", "analysis", "how_to"]
      emotional: ["creative", "personal", "opinion", "advice"]
      balanced: ["general", "conversation", "explanation"]
  factuality_checker:
    verification_threshold: 0.7
    max_corrections: 3
    enable_auto_correction: true
    verification_model: language
    max_claims_to_verify: 5

# Configuración del cerebro dual
dual_brain:
  enabled: true               # Activar cerebro dual
  config_path: "/opt/vokaflow/config/dual_brain.yaml"
  technical_weight: 0.55      # Ligeramente favorecido para precisión técnica
  emotional_weight: 0.45      # Manteniendo buena capacidad de empatía
  combination_strategy: "integrated"
  parallel_processing: true

# Configuración de plugins optimizada
plugins:
  enabled:
    - core
    - translation
    - voice
    - memory
  
  settings:
    translation:
      default_target_language: es
      cache_translations: true
      batch_processing: true   # Procesar traducciones en lotes cuando sea posible
      auto_detect_threshold: 0.8  # Umbral para detección automática de idioma
    
    voice:
      activation_word: vicky
      voice_id: es_female_1
      noise_reduction: true    # Reducción de ruido para mejor reconocimiento
      vad_sensitivity: 3       # Sensibilidad de detección de actividad de voz (1-5)
      response_speed: "balanced"  # Balance entre velocidad y calidad
    
    memory:
      max_history: 200         # Aumentado para mejor contexto a largo plazo
      vector_db_path: /cache/vokaflow_data/vector_db
      index_type: "hnsw"       # Algoritmo de indexación eficiente
      similarity_metric: "cosine"  # Métrica de similitud óptima
      refresh_interval: 3600   # Actualizar índices cada hora

# Configuración de rendimiento del sistema
performance:
  memory_management:
    gc_interval: 300           # Intervalo de recolección de basura (segundos)
    max_memory_usage: 0.8      # Uso máximo de memoria (fracción del total)
    preload_critical_models: true  # Precargar modelos críticos
  
  threading:
    worker_threads: 4          # Número óptimo de hilos de trabajo
    queue_size: 100            # Tamaño de cola de tareas
    priority_scheduling: true  # Programación por prioridad
  
  caching:
    response_cache_size: 150   # Tamaño de caché de respuestas
    embedding_cache_size: 500  # Tamaño de caché de embeddings
    model_cache_size: 2        # Número de modelos a mantener en caché

# Configuración de logging optimizada
logging:
  file_rotation: true          # Rotación de archivos de log
  max_file_size: 10485760      # 10 MB por archivo
  backup_count: 5              # Número de backups
  performance_metrics: true    # Registrar métricas de rendimiento
  log_level: INFO              # Nivel de log normal
  debug_mode: false            # Modo debug desactivado en producción
