#!/bin/bash

# Script de ayuda para usar la Kinect en Vokaflow

clear
echo "===== GUÍA DE USO DE KINECT EN VOKAFLOW ====="
echo ""
echo "SCRIPTS DISPONIBLES:"
echo "-------------------"
echo "1. estado_kinect.sh - Verificar el estado de la Kinect y las herramientas instaladas"
echo "   Uso: ./scripts/estado_kinect.sh"
echo ""
echo "2. mover_kinect.sh - Mover el motor de la Kinect a un ángulo específico"
echo "   Uso: ./scripts/mover_kinect.sh <ángulo>"
echo "   Ejemplo: ./scripts/mover_kinect.sh 15 (mover hacia arriba 15 grados)"
echo "   Ejemplo: ./scripts/mover_kinect.sh -10 (mover hacia abajo 10 grados)"
echo ""
echo "3. capturar_kinect.sh - Capturar una imagen desde la Kinect"
echo "   Uso: ./scripts/capturar_kinect.sh"
echo "   Las imágenes se guardarán en /opt/vokaflow/data/kinect_captures/"
echo ""
echo "HERRAMIENTAS ADICIONALES:"
echo "------------------------"
echo "1. freenect-camtest - Capturar imágenes en tiempo real (usa Ctrl+C para salir)"
echo "   Uso: freenect-camtest"
echo ""
echo "2. freenect-tiltdemo - Controlar el motor de la Kinect manualmente"
echo "   Uso: freenect-tiltdemo"
echo "   Controles: w (arriba), x (abajo), 0-6 (cambiar LEDs), q (salir)"
echo ""
echo "3. freenect-glview - Visualizar imágenes RGB y de profundidad (requiere X)"
echo "   Uso: freenect-glview"
echo ""
echo "CONFIGURACIÓN AUTOMÁTICA:"
echo "------------------------"
echo "La Kinect se configura automáticamente al inicio del sistema mediante"
echo "el servicio kinect-setup.service, que establece los permisos necesarios."
echo ""
echo "Para verificar el estado del servicio:"
echo "   sudo systemctl status kinect-setup.service"
echo ""
echo "Para más información, consulta la documentación de libfreenect."
echo "===== FIN DE LA AYUDA =====" 